import { useCallback, useEffect, useRef, useState } from 'react'

type State='idle'|'waiting'|'stabilizing'|'capturing'|'processing'|'remove'
export function useAutoScanner(onCapture:(blob:Blob)=>Promise<void>) {
  const video=useRef<HTMLVideoElement>(null), canvas=useRef<HTMLCanvasElement>(null), previous=useRef<Uint8ClampedArray|undefined>(undefined), stable=useRef(0), latched=useRef(false), busy=useRef(false)
  const [state,setState]=useState<State>('idle'), [error,setError]=useState<string>()
  const start=useCallback(async()=>{ try { const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:'environment'},audio:false}); if(video.current){video.current.srcObject=stream; await video.current.play(); setState('waiting')} } catch(e){setError(e instanceof Error?e.message:'Camera unavailable')} },[])
  const stop=useCallback(()=>{(video.current?.srcObject as MediaStream|null)?.getTracks().forEach(t=>t.stop()); setState('idle')},[])
  useEffect(()=>{ if(state==='idle'||error)return; const timer=setInterval(async()=>{const v=video.current,c=canvas.current;if(!v||!c||v.readyState<2||busy.current)return;const ctx=c.getContext('2d',{willReadFrequently:true});if(!ctx)return;c.width=160;c.height=120;ctx.drawImage(v,0,0,160,120);const pixels=ctx.getImageData(0,0,160,120).data;let brightness=0,variance=0,difference=0;for(let i=0;i<pixels.length;i+=16){const lum=(pixels[i]+pixels[i+1]+pixels[i+2])/3;brightness+=lum;variance+=lum*lum;if(previous.current)difference+=Math.abs(pixels[i]-previous.current[i])}const samples=pixels.length/16, motion=previous.current?difference/samples:99, mean=brightness/samples,contrast=Math.sqrt(Math.max(0,variance/samples-mean*mean));previous.current=new Uint8ClampedArray(pixels);const present=mean>25&&contrast>18;if(latched.current){if(motion>8){stable.current++;if(stable.current>=3){latched.current=false;stable.current=0;setState('waiting')}}else stable.current=0;return}if(!present){setState('waiting');stable.current=0;return}if(motion<2.2){stable.current++;setState('stabilizing')}else{stable.current=0;setState('waiting')}if(stable.current>=5){busy.current=true;setState('capturing');const full=document.createElement('canvas');full.width=v.videoWidth;full.height=v.videoHeight;full.getContext('2d')!.drawImage(v,0,0);full.toBlob(async blob=>{if(blob){setState('processing');try{await onCapture(blob)}catch(e){setError(e instanceof Error?e.message:'Scan failed')}}latched.current=true;busy.current=false;stable.current=0;setState('remove')},'image/jpeg',.9)}},180);return()=>clearInterval(timer)},[state,error,onCapture])
  useEffect(()=>stop, [stop])
  return {video,canvas,state,error,start,stop,setError}
}
