import { describe,expect,it } from 'vitest'
import type { GameState } from '../types'
import { classifyNoticeTone,presentationNoticeDuration,presentationNotices,visualStateDiff } from './visualTransition'

const state=(life=20,phase='precombat_main',cards:string[]=[]):GameState=>({version:1,status:'active',winner_id:null,turn:1,phase,active_player_id:'player',priority_player_id:'player',players:[{id:'player',name:'You',is_bot:false,format:'standard',life,poison:0,hand:[],library_count:50,battlefield:cards.map(instance_id=>({instance_id,scryfall_id:instance_id,name:instance_id,image_url:null,type_line:'Creature',oracle_text:'',mana_cost:'',mana_value:1,keywords:[],power:'1',toughness:'1',tapped:false,damage:0,counters:{},summoning_sick:false})),graveyard:[],exile:[],command:[],commander_casts:0,commander_damage:{},land_plays_remaining:1,kept_hand:true,mulligans:0,lost:false},{id:'bot',name:'Bot',is_bot:true,format:'standard',life:20,poison:0,hand:[],library_count:50,battlefield:[],graveyard:[],exile:[],command:[],commander_casts:0,commander_damage:{},land_plays_remaining:1,kept_hand:true,mulligans:0,lost:false}],stack:[],combat:{attackers:[],blocks:{},attack_targets:{},block_orders:{},damage_pending:false},consecutive_passes:0,pending_phase_advance:false,pending_discard:null,pending_mulligan_bottom:null,pending_sacrifice:null,pending_legendary:null,pending_library_search:null,pending_scry:null,pending_damage_order:null,pending_ward:null,pending_trigger_targets:[],log:[]})

describe('Play visual transitions',()=>{
  it('keeps automatic event banners visible long enough to read',()=>{expect(presentationNoticeDuration({id:'short',text:'A creature died.',tone:'danger'})).toBeGreaterThanOrEqual(3000);expect(presentationNoticeDuration({id:'long',text:'Whenever this creature enters the battlefield each opponent discards a card and loses two life.',tone:'stack'})).toBeGreaterThan(3000);expect(presentationNoticeDuration({id:'phase',text:'Turn 2 · Combat',tone:'phase'})).toBe(2400)})
  it('identifies newly entered cards and changed life totals',()=>{const diff=visualStateDiff(state(20,'precombat_main',['old']),state(17,'precombat_main',['old','new']));expect([...diff.enteringIds]).toEqual(['new']);expect([...diff.impactedPlayerIds]).toEqual(['player']);expect(diff.phaseChanged).toBe(false)})
  it('prioritizes phase feedback and classifies gameplay outcomes',()=>{expect(classifyNoticeTone('anything',true)).toBe('phase');expect(classifyNoticeTone('You gained 3 life.',false)).toBe('good');expect(classifyNoticeTone('A creature was destroyed.',false)).toBe('danger');expect(classifyNoticeTone('You cast a spell.',false)).toBe('stack')})
  it('queues every unseen event before the phase banner',()=>{const previous=state(),current={...state(17,'combat'),version:4,log:[{id:'one',turn:1,message:'Bot cast a spell.'},{id:'two',turn:1,message:'You lost 3 life.'}]};expect(presentationNotices(previous,current,'Combat').map(notice=>notice.text)).toEqual(['Bot cast a spell.','You lost 3 life.','Turn 1 · Combat'])})
})
