import { useEffect, useState } from 'react'
import { Alert, Box, Card, CardContent, Chip, Grid, LinearProgress, MenuItem, Select, Skeleton, Stack, Typography } from '@mui/material'
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { request } from '../api'
import { CardName } from '../components/CardDetails'
import type { Inventory, ReferenceStatus } from '../types'
type Group={label:string;count:number}
type Summary={total_value:number;total_cards:number;unique_printings:number;review_count:number;by_set:Group[];by_color:Group[];by_rarity:Group[];by_type:Group[];most_valuable:Inventory[];newest:Inventory[];duplicate_cards:Inventory[]}
const duration=(seconds:number)=>{const hours=Math.floor(seconds/3600),minutes=Math.max(1,Math.round(seconds%3600/60));return hours?`${hours}h ${minutes}m`:`${minutes}m`}

export default function Dashboard(){
  const [data,setData]=useState<Summary>(),[references,setReferences]=useState<ReferenceStatus>(),[breakdown,setBreakdown]=useState<'by_set'|'by_color'|'by_rarity'|'by_type'>('by_set')
  useEffect(()=>{request<Summary>('/dashboard/summary').then(setData)},[])
  useEffect(()=>{const refresh=()=>request<ReferenceStatus>('/references/status').then(setReferences);void refresh();const timer=setInterval(refresh,2500);return()=>clearInterval(timer)},[])
  if(!data)return <Skeleton height={500}/>
  return <><Typography variant="h4" mb={3}>Collection overview</Typography><Grid container spacing={2}>{[['Total value',`$${Number(data.total_value).toLocaleString(undefined,{minimumFractionDigits:2})}`],['Cards',data.total_cards],['Unique printings',data.unique_printings],['Needs review',data.review_count]].map(([label,value])=><Grid size={{xs:6,md:3}} key={label}><Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4">{value}</Typography></CardContent></Card></Grid>)}</Grid>
    <Grid container spacing={3} mt={.5}>
      <Grid size={{xs:12}}><Card><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={2}><Box><Typography variant="h6">Recognition database</Typography><Typography color="text.secondary">Canonical MTG printing visuals used to distinguish artwork, frames, set symbols, and collector footers.</Typography></Box><Stack direction="row" spacing={1} alignItems="center"><Chip color={references?.state==='running'?'primary':references?.state==='failed'?'error':references?.coverage_percent===100?'success':'warning'} label={references?.state==='running'?'Updating now':references?.state==='failed'?'Update interrupted':references?.coverage_percent===100?'Up to date':'Incomplete'}/>{references?.set_code&&<Chip variant="outlined" label={references.set_code.replace('priority:','').toUpperCase()}/>}</Stack></Stack>
        <Stack direction={{xs:'column',sm:'row'}} spacing={{xs:1,sm:4}} mt={2}><Box><Typography variant="h4">{(references?.fingerprinted_cards||0).toLocaleString()}<Typography component="span" color="text.secondary" fontSize="1rem"> / {references?.catalog_total?.toLocaleString()||'—'}</Typography></Typography><Typography color="text.secondary">visual printings saved</Typography></Box><Box><Typography variant="h4">{references?.indexed_sets||0}</Typography><Typography color="text.secondary">sets represented</Typography></Box><Box><Typography variant="h4">{references?.errors||0}</Typography><Typography color="text.secondary">sync errors</Typography></Box></Stack>
        <LinearProgress variant={references?.catalog_total?'determinate':'indeterminate'} value={references?.coverage_percent||0} sx={{mt:2,height:9,borderRadius:99}}/><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" mt={.75} spacing={.5}><Typography variant="caption" color="text.secondary">{references?.coverage_percent==null?'Discovering catalog size':`${references.coverage_percent.toFixed(2)}% of Scryfall paper printings`}</Typography><Typography variant="caption" color="text.secondary">{references?.state==='running'?`${references.completed.toLocaleString()} records checked this pass`:references?.updated_at?`Updated ${new Date(references.updated_at).toLocaleString()}`:''}</Typography></Stack>
        {references?.state==='running'&&references.estimated_seconds_remaining!=null&&<Typography mt={1.25} fontWeight={800} color="primary.main">Estimated time remaining · about {duration(references.estimated_seconds_remaining)} · {references.estimated_completion_at?new Date(references.estimated_completion_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):''}<Typography component="span" color="text.secondary" fontWeight={400}> at {references.indexing_rate_per_second?.toFixed(1)} images/sec</Typography></Typography>}{references?.state==='failed'&&<Alert severity="error" sx={{mt:2}}>{references.error||'Catalog update was interrupted and will retry automatically.'}</Alert>}
      </CardContent></Card></Grid>
      <Grid size={{xs:12,md:7}}><Card sx={{height:410}}><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h6">Collection breakdown</Typography><Select size="small" value={breakdown} onChange={e=>setBreakdown(e.target.value as typeof breakdown)}><MenuItem value="by_set">By set</MenuItem><MenuItem value="by_color">By color</MenuItem><MenuItem value="by_rarity">By rarity</MenuItem><MenuItem value="by_type">By type</MenuItem></Select></Stack><Box height={320} mt={2}><ResponsiveContainer><BarChart data={data[breakdown].slice(0,10)}><XAxis dataKey="label" tick={{fontSize:11}}/><YAxis/><Tooltip/><Bar dataKey="count" fill="#D63A4B" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></Box></CardContent></Card></Grid>
      <Grid size={{xs:12,md:5}}><Card sx={{height:410}}><CardContent sx={{height:'100%',display:'flex',flexDirection:'column'}}><Typography variant="h6">Most valuable</Typography><Box sx={{overflowY:'auto',pr:1,mt:.5}}>{data.most_valuable.map(x=><Stack direction="row" justifyContent="space-between" mt={2} key={x.id}><Box minWidth={0}><Typography fontWeight={700} noWrap><CardName scryfallId={x.scryfall_id}>{x.card_name}</CardName></Typography><Typography variant="caption" color="text.secondary">{x.set_code.toUpperCase()} #{x.collector_number} · ×{x.quantity}</Typography></Box><Typography color="primary.main" fontWeight={800}>${Number(x.market_price).toFixed(2)}</Typography></Stack>)}</Box></CardContent></Card></Grid>
      <Grid size={{xs:12,md:6}}><Card><CardContent><Typography variant="h6">Newest cards</Typography>{data.newest.map(x=><Stack direction="row" justifyContent="space-between" mt={1.5} key={x.id}><Typography fontWeight={700}><CardName scryfallId={x.scryfall_id}>{x.card_name}</CardName></Typography><Typography variant="caption" color="text.secondary">{x.set_code.toUpperCase()} #{x.collector_number}</Typography></Stack>)}</CardContent></Card></Grid>
      <Grid size={{xs:12,md:6}}><Card><CardContent><Typography variant="h6">Duplicate printings</Typography>{data.duplicate_cards.map(x=><Stack direction="row" justifyContent="space-between" mt={1.5} key={x.id}><Typography fontWeight={700}><CardName scryfallId={x.scryfall_id}>{x.card_name}</CardName></Typography><Typography color="primary.main" fontWeight={800}>×{x.quantity}</Typography></Stack>)}{!data.duplicate_cards.length&&<Typography color="text.secondary" mt={2}>No duplicate printings yet.</Typography>}</CardContent></Card></Grid>
    </Grid></>
}
