import { useEffect, useMemo, useState } from 'react'
import { ArrowDownward, ArrowUpward, AutoAwesome, Bolt, Build, ContentCopy, Delete, Favorite, History, People, PlayArrow, Refresh, Replay, Shield, SmartToy, SportsEsports } from '@mui/icons-material'
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControlLabel, Grid, IconButton, MenuItem, Paper, Stack, Switch, TextField, Tooltip, Typography } from '@mui/material'
import { request } from '../api'
import type { Deck, Game, GameCard, GameMode, GamePlayer, GameTarget, LegalGameAction } from '../types'

const phases=[['beginning','Upkeep · draw next'],['precombat_main','Main 1'],['combat','Combat'],['postcombat_main','Main 2'],['ending','End turn']]
const isMeaningfulChoice=(action:LegalGameAction)=>{
  if(['advance_phase','resolve_combat_damage','adjust_life','add_counter','move_zone','create_token','concede'].includes(action.type))return false
  if(['declare_attackers','declare_blockers'].includes(action.type))return !!action.card_ids?.length
  return true
}

function ZoneCard({card,legal,onClick,attacking=false,blocked=false,selected=false}:{card:GameCard;legal?:boolean;onClick?:()=>void;attacking?:boolean;blocked?:boolean;selected?:boolean}){
  return <Tooltip title={<><b>{card.name}</b><br/>{card.type_line}{card.effective_power!==undefined&&<><br/><b>{card.effective_power}/{card.effective_toughness}</b></>}<br/>{card.oracle_text}</>} placement="top" arrow>
    <Box className={`play-card ${card.tapped?'is-tapped':''} ${legal?'is-legal':''} ${attacking?'is-attacking':''} ${selected?'is-selected':''}`} onClick={onClick} role={legal?'button':undefined} aria-label={card.name}>
      <Box component="img" src={card.image_url||''} alt={card.name}/>
      {(card.damage>0||Object.values(card.counters||{}).some(Boolean))&&<Chip className="play-counter" size="small" color={card.damage?'error':'success'} label={card.damage?`${card.damage} dmg`:Object.entries(card.counters).filter(([,amount])=>amount).map(([name,amount])=>`${amount} ${name}`).join(', ')}/>} {card.effective_power!==undefined&&<Chip className="play-stats" size="small" label={`${card.effective_power}/${card.effective_toughness}`}/>} {blocked&&<Chip className="play-blocked" size="small" label="Blocked"/>}
    </Box>
  </Tooltip>
}

function HiddenHand({count=0}:{count?:number}){return <Stack direction="row" justifyContent="center" className="hidden-hand">{Array.from({length:Math.min(count,12)},(_,index)=><Box key={index} className="card-back" sx={{ml:index?-4:0}}/>)}</Stack>}

function Battlefield({player,game,onCard,selectableIds=new Set(),selectedIds=new Set(),onSelect}:{player:GamePlayer;game:Game;onCard:(card:GameCard)=>void;selectableIds?:Set<string>;selectedIds?:Set<string>;onSelect?:(card:GameCard)=>void}){
  const attackers=new Set(game.state.combat.attackers),blocked=new Set(Object.values(game.state.combat.blocks))
  const creatures=player.battlefield.filter(card=>!card.type_line.includes('Land')),lands=player.battlefield.filter(card=>card.type_line.includes('Land'))
  return <Box className="battlefield-zone">
    <Stack direction="row" className="permanent-row" justifyContent="center">{creatures.map(card=>{const selectable=selectableIds.has(card.instance_id),legal=selectable||game.legal_actions.some(action=>action.card_id===card.instance_id);return <ZoneCard key={card.instance_id} card={card} legal={legal} selected={selectedIds.has(card.instance_id)} onClick={()=>selectable&&onSelect?onSelect(card):onCard(card)} attacking={attackers.has(card.instance_id)} blocked={blocked.has(card.instance_id)}/>})}</Stack>
    <Stack direction="row" className="land-row" justifyContent="center">{lands.map(card=>{const legal=game.legal_actions.some(action=>action.card_id===card.instance_id);return <ZoneCard key={card.instance_id} card={card} legal={legal} onClick={()=>onCard(card)}/>})}</Stack>
  </Box>
}

export default function Play(){
  const [decks,setDecks]=useState<Deck[]>([]),[games,setGames]=useState<Game[]>([]),[game,setGame]=useState<Game>(),[busy,setBusy]=useState(false),[error,setError]=useState<string>()
  const [setup,setSetup]=useState({name:'Game vs Bot',player_deck_id:'',opponent_deck_id:'',bot_difficulty:'standard',opponent_type:'bot',bot_deck_mode:'generated',play_first:true})
  const [inviteUrl,setInviteUrl]=useState(''),[targetChoice,setTargetChoice]=useState<{action:LegalGameAction;targets:GameTarget[]}>()
  const [abilityChoices,setAbilityChoices]=useState<LegalGameAction[]>([])
  const [modeChoice,setModeChoice]=useState<LegalGameAction>(),[selectedModes,setSelectedModes]=useState<number[]>([])
  const [modalTargetChoice,setModalTargetChoice]=useState<{action:LegalGameAction;modes:GameMode[];position:number;targets:Array<string|null>}>()
  const [costChoice,setCostChoice]=useState<LegalGameAction>(),[selectedCosts,setSelectedCosts]=useState<string[]>([])
  const [hostToken,setHostToken]=useState('')
  const [selectedAttackers,setSelectedAttackers]=useState<string[]>([]),[blocks,setBlocks]=useState<Record<string,string>>({}),[choosingBlocker,setChoosingBlocker]=useState<string>()
  const [attackTargets,setAttackTargets]=useState<Record<string,string>>({}),[attackDialog,setAttackDialog]=useState(false)
  const [selectedDiscards,setSelectedDiscards]=useState<string[]>([])
  const [selectedSacrifices,setSelectedSacrifices]=useState<string[]>([])
  const [selectedLegendary,setSelectedLegendary]=useState<string[]>([])
  const [scryOrder,setScryOrder]=useState<string[]>([]),[scryBottom,setScryBottom]=useState<string[]>([])
  const [blockOrders,setBlockOrders]=useState<Record<string,string[]>>({})
  const [toolsOpen,setToolsOpen]=useState(false),[toolForm,setToolForm]=useState({target_id:'',counter_name:'+1/+1',amount:1,token_name:'Creature Token',power:1,toughness:1,destination:'graveyard'})
  const query=new URLSearchParams(location.search),inviteCode=query.get('invite'),inviteToken=query.get('token'),isGuest=!!inviteCode&&!!inviteToken,viewerId=isGuest?'bot':'player',opponentId=isGuest?'player':'bot'
  const credentials=(id:string)=>{const raw=localStorage.getItem(`mtglogger-invite-${id}`)||'';if(!raw)return{hostToken:'',inviteUrl:''};try{return JSON.parse(raw) as {hostToken:string;inviteUrl:string}}catch{return{hostToken:'',inviteUrl:raw}}}
  const load=async()=>{const [deckData,gameData]=await Promise.all([request<Deck[]>('/decks'),request<Game[]>('/play')]);setDecks(deckData.filter(deck=>deck.total_cards>0));setGames(gameData);setSetup(current=>({...current,player_deck_id:current.player_deck_id||deckData[0]?.id||'',opponent_deck_id:current.opponent_deck_id||deckData[1]?.id||deckData[0]?.id||''}))}
  const accessToken=isGuest?inviteToken||'':hostToken,authHeaders:Record<string,string>=accessToken?{'X-Game-Token':accessToken}:{},gamePath=isGuest?`/play/invite/${inviteCode}/state`:game?`/play/${game.id}`:''
  useEffect(()=>{if(isGuest){request<Game>(`/play/invite/${inviteCode}/state`,{headers:{'X-Game-Token':inviteToken||''}}).then(setGame).catch(e=>setError(e.message))}else void load().catch(e=>setError(e.message))},[])
  useEffect(()=>{if(!game||game.opponent_type!=='human')return;const timer=setInterval(()=>request<Game>(gamePath,{headers:authHeaders}).then(setGame).catch(()=>undefined),1800);return()=>clearInterval(timer)},[game?.id,gamePath,accessToken])
  useEffect(()=>{
    if(!game||busy||game.state.status!=='active'||game.state.priority_player_id!==viewerId)return
    const automatic=game.legal_actions.find(action=>action.type==='resolve_combat_damage')||game.legal_actions.find(action=>action.type==='advance_phase')
    const decisions=game.legal_actions.filter(isMeaningfulChoice)
    if(!automatic||decisions.length)return
    const timer=setTimeout(()=>void act({type:automatic.type}),350)
    return()=>clearTimeout(timer)
  },[game?.state.version,busy,viewerId])
  useEffect(()=>{setSelectedAttackers([]);setBlocks({});setChoosingBlocker(undefined);setAttackTargets({});setAttackDialog(false);setAbilityChoices([]);setModeChoice(undefined);setSelectedModes([]);setModalTargetChoice(undefined);setCostChoice(undefined);setSelectedCosts([]);setSelectedDiscards([]);setSelectedSacrifices([]);setSelectedLegendary([]);setScryOrder([]);setScryBottom([]);setBlockOrders({})},[game?.state.version])
  const act=async(action:Record<string,unknown>)=>{if(!game)return;setBusy(true);setError(undefined);try{const path=isGuest?`/play/invite/${inviteCode}/actions`:`/play/${game.id}/actions`;setGame(await request<Game>(path,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders},body:JSON.stringify({...action,expected_version:game.state.version})}))}catch(e){setError(e instanceof Error?e.message:'The action could not be completed');if(e instanceof Error&&e.message.includes('other browser'))void request<Game>(gamePath,{headers:authHeaders}).then(setGame)}finally{setBusy(false)}}
  const create=async()=>{setBusy(true);setError(undefined);try{const created=await request<Game>('/play',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(setup)});setGame(created);if(created.invite_code&&created.invite_token&&created.host_token){const url=`${location.origin}${location.pathname}?page=play&invite=${encodeURIComponent(created.invite_code)}&token=${encodeURIComponent(created.invite_token)}`;localStorage.setItem(`mtglogger-invite-${created.id}`,JSON.stringify({hostToken:created.host_token,inviteUrl:url}));setHostToken(created.host_token);setInviteUrl(url)}}catch(e){setError(e instanceof Error?e.message:'Could not start the game')}finally{setBusy(false)}}
  const undo=async()=>{if(!game||isGuest)return;setBusy(true);try{setGame(await request<Game>(`/play/${game.id}/undo`,{method:'POST',headers:authHeaders}))}catch(e){setError(e instanceof Error?e.message:'Nothing to undo')}finally{setBusy(false)}}
  const remove=async(id:string)=>{const saved=games.find(item=>item.id===id),token=credentials(id).hostToken;await request(`/play/${id}`,{method:'DELETE',headers:saved?.opponent_type==='human'?{'X-Game-Token':token}:{}});localStorage.removeItem(`mtglogger-invite-${id}`);if(game?.id===id)setGame(undefined);await load()}
  const resume=async(saved:Game)=>{const stored=credentials(saved.id);setHostToken(stored.hostToken);setInviteUrl(stored.inviteUrl);if(saved.opponent_type==='human'){if(!stored.hostToken){setError('This browser does not have the host key for that private game. Open it from the browser that created it.');return}setGame(await request<Game>(`/play/${saved.id}`,{headers:{'X-Game-Token':stored.hostToken}}))}else setGame(saved)}
  const rotateInvite=async()=>{if(!game||!hostToken)return;const updated=await request<Game>(`/play/${game.id}/invite/rotate`,{method:'POST',headers:{'X-Game-Token':hostToken}});if(updated.invite_code&&updated.invite_token){const url=`${location.origin}${location.pathname}?page=play&invite=${encodeURIComponent(updated.invite_code)}&token=${encodeURIComponent(updated.invite_token)}`;localStorage.setItem(`mtglogger-invite-${game.id}`,JSON.stringify({hostToken,inviteUrl:url}));setInviteUrl(url);setGame(updated)}}
  const legal=(type:string,cardId?:string)=>game?.legal_actions.some(action=>action.type===type&&(!cardId||action.card_id===cardId))
  const player=game?.state.players.find(item=>item.id===viewerId),bot=game?.state.players.find(item=>item.id===opponentId)
  const phase=phases.find(([key])=>key===game?.state.phase)?.[1]
  const attackAction=game?.legal_actions.find(action=>action.type==='declare_attackers'),blockAction=game?.legal_actions.find(action=>action.type==='declare_blockers')
  const discardAction=game?.legal_actions.find(action=>action.type==='discard_cards')
  const mulliganBottomAction=game?.legal_actions.find(action=>action.type==='bottom_mulligan_cards'),handChoiceAction=discardAction||mulliganBottomAction
  const sacrificeAction=game?.legal_actions.find(action=>action.type==='sacrifice_permanents')
  const legendaryAction=game?.legal_actions.find(action=>action.type==='choose_legendary')
  const scryAction=game?.legal_actions.find(action=>action.type==='scry'||action.type==='surveil')
  const blockOrderAction=game?.legal_actions.find(action=>action.type==='order_blockers')
  const payWardAction=game?.legal_actions.find(action=>action.type==='pay_ward'),declineWardAction=game?.legal_actions.find(action=>action.type==='decline_ward'),wardAction=payWardAction||declineWardAction
  const triggerTargetAction=game?.legal_actions.find(action=>action.type==='choose_trigger_target'),skipTriggerAction=game?.legal_actions.find(action=>action.type==='skip_trigger')
  const autoAdvancing=!!game?.legal_actions.some(action=>action.type==='advance_phase'||action.type==='resolve_combat_damage')&&!game?.legal_actions.some(isMeaningfulChoice)&&game.state.priority_player_id===viewerId
  const humanActive=game?.state.active_player_id===viewerId
  const winner=game?.state.players.find(item=>item.id===game.state.winner_id)
  const gameTitle=useMemo(()=>decks.find(deck=>deck.id===game?.player_deck_id)?.name,[decks,game])
  const submitCardAction=(action:LegalGameAction)=>{if(action.targets?.length)setTargetChoice({action,targets:action.targets});else void act({type:action.type,card_id:action.card_id,ability_index:action.ability_index,cost_card_ids:action.cost_card_ids||[],chosen_modes:action.chosen_modes||[],mode_targets:action.mode_targets||[],source:player?.command.some(item=>item.instance_id===action.card_id)?'command':action.source||'hand'})}
  const executeCardAction=(action:LegalGameAction)=>{if(action.modes?.length){setModeChoice(action);setSelectedModes([])}else if(action.cost_options?.length){setCostChoice(action);setSelectedCosts([])}else submitCardAction(action)}
  const confirmModes=()=>{if(!modeChoice)return;const chosen=selectedModes.map(index=>modeChoice.modes?.find(mode=>mode.index===index)).filter((mode):mode is GameMode=>!!mode),action={...modeChoice,modes:undefined,chosen_modes:selectedModes};setModeChoice(undefined);setSelectedModes([]);const firstTargeted=chosen.findIndex(mode=>mode.targets?.length);if(firstTargeted>=0){setModalTargetChoice({action,modes:chosen,position:firstTargeted,targets:chosen.map(()=>null)});return}executeCardAction({...action,mode_targets:chosen.map(()=>null)})}
  const chooseModalTarget=(targetId:string)=>{if(!modalTargetChoice)return;const targets=[...modalTargetChoice.targets];targets[modalTargetChoice.position]=targetId;const next=modalTargetChoice.modes.findIndex((mode,index)=>index>modalTargetChoice.position&&mode.targets?.length);if(next>=0){setModalTargetChoice({...modalTargetChoice,position:next,targets});return}setModalTargetChoice(undefined);executeCardAction({...modalTargetChoice.action,mode_targets:targets})}
  const playCard=(card:GameCard)=>{const actions=game?.legal_actions.filter(item=>item.card_id===card.instance_id)||[];if(!actions.length)return;if(actions.length>1){setAbilityChoices(actions);return}executeCardAction(actions[0])}
  const automaticBlocks=()=>{const result:Record<string,string>={},remaining=[...(blockAction?.card_ids||[])];for(const attacker of game?.state.combat.attackers||[]){const eligible=remaining.filter(blocker=>blockAction?.legal_blocks?.[blocker]?.includes(attacker));const attackingCard=bot?.battlefield.find(card=>card.instance_id===attacker),needed=(attackingCard?.keywords||[]).some(keyword=>keyword.toLowerCase()==='menace')?2:1;for(const blocker of eligible.slice(0,needed)){result[blocker]=attacker;remaining.splice(remaining.indexOf(blocker),1)}}return result}
  const attackerIds=new Set(attackAction?.card_ids||[]),blockerIds=new Set(blockAction?.card_ids||[]),selectedIds=new Set(selectedAttackers)
  const toggleAttacker=(card:GameCard)=>setSelectedAttackers(current=>current.includes(card.instance_id)?current.filter(id=>id!==card.instance_id):[...current,card.instance_id])
  const prepareAttack=()=>{if(!selectedAttackers.length){void act({type:'declare_attackers',attacker_ids:[]});return}const defenders=attackAction?.defenders||[];if(defenders.length<=1){void act({type:'declare_attackers',attacker_ids:selectedAttackers,attack_targets:Object.fromEntries(selectedAttackers.map(id=>[id,defenders[0]?.id||opponentId]))});return}setAttackTargets(Object.fromEntries(selectedAttackers.map(id=>[id,defenders[0].id])));setAttackDialog(true)}
  const assignBlock=(attackerId?:string)=>{if(!choosingBlocker)return;setBlocks(current=>{const next={...current};if(attackerId)next[choosingBlocker]=attackerId;else delete next[choosingBlocker];return next});setChoosingBlocker(undefined)}
  const menaceInvalid=Object.entries(blocks).some(([,attackerId])=>{const card=bot?.battlefield.find(item=>item.instance_id===attackerId);return card?.keywords.some(keyword=>keyword.toLowerCase()==='menace')&&Object.values(blocks).filter(id=>id===attackerId).length===1})
  const visibleCards=game?.state.players.flatMap(owner=>['hand','battlefield','graveyard','exile'].flatMap(zone=>(owner[zone as keyof GamePlayer] as GameCard[]).map(card=>({card,owner:owner.name,zone}))))||[]
  const orderedScryCards=(scryOrder.length?scryOrder:scryAction?.card_ids||[]).map(id=>scryAction?.cards?.find(card=>card.instance_id===id)).filter((card):card is GameCard=>!!card)
  const moveScry=(index:number,direction:number)=>setScryOrder(current=>{const next=[...(current.length?current:scryAction?.card_ids||[])],target=index+direction;if(target<0||target>=next.length)return next;[next[index],next[target]]=[next[target],next[index]];return next})
  const moveBlocker=(attackerId:string,defaults:string[],index:number,direction:number)=>setBlockOrders(current=>{const order=[...(current[attackerId]||defaults)],target=index+direction;if(target<0||target>=order.length)return current;[order[index],order[target]]=[order[target],order[index]];return{...current,[attackerId]:order}})

  if(!game)return <Box>
    <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Typography variant="h3">Play</Typography><Typography color="text.secondary">Play your physical collection virtually with database artwork and automatic rules assistance.</Typography></Box><Chip icon={<AutoAwesome/>} color="primary" label="Rules engine · Bots · Private invites" sx={{alignSelf:'flex-start'}}/></Stack>
    {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
    <Grid container spacing={2.5}>
      <Grid size={{xs:12,md:7}}><Card variant="outlined"><CardContent><Stack direction="row" spacing={1} alignItems="center" mb={2}>{setup.opponent_type==='bot'?<SmartToy color="primary"/>:<People color="primary"/>}<Typography variant="h5">New {setup.opponent_type==='bot'?'bot':'private'} game</Typography></Stack><Grid container spacing={2}>
        <Grid size={{xs:12}}><TextField fullWidth label="Game name" value={setup.name} onChange={e=>setSetup({...setup,name:e.target.value})}/></Grid>
        <Grid size={{xs:12,sm:6}}><TextField select fullWidth label="Your deck" value={setup.player_deck_id} onChange={e=>setSetup({...setup,player_deck_id:e.target.value})}>{decks.map(deck=><MenuItem key={deck.id} value={deck.id}>{deck.name} · {deck.total_cards} cards</MenuItem>)}</TextField></Grid>
        {setup.opponent_type==='bot'&&<Grid size={{xs:12,sm:6}}><TextField select fullWidth label="Bot deck" value={setup.bot_deck_mode} onChange={e=>setSetup({...setup,bot_deck_mode:e.target.value})}><MenuItem value="generated">Auto-build a fresh bot deck</MenuItem><MenuItem value="existing">Use one of my decks</MenuItem></TextField></Grid>}
        {(setup.opponent_type==='human'||setup.bot_deck_mode==='existing')&&<Grid size={{xs:12,sm:6}}><TextField select fullWidth label={setup.opponent_type==='bot'?'Choose bot deck':'Guest deck'} value={setup.opponent_deck_id} onChange={e=>setSetup({...setup,opponent_deck_id:e.target.value})}>{decks.map(deck=><MenuItem key={deck.id} value={deck.id}>{deck.name} · {deck.total_cards} cards</MenuItem>)}</TextField></Grid>}
        <Grid size={{xs:12,sm:6}}><TextField select fullWidth label="Opponent" value={setup.opponent_type} onChange={e=>setSetup({...setup,opponent_type:e.target.value,name:e.target.value==='bot'?'Game vs Bot':'Private game'})}><MenuItem value="bot">Bot opponent</MenuItem><MenuItem value="human">Invite a player</MenuItem></TextField></Grid>
        {setup.opponent_type==='bot'&&<Grid size={{xs:12,sm:6}}><TextField select fullWidth label="Bot difficulty" value={setup.bot_difficulty} onChange={e=>setSetup({...setup,bot_difficulty:e.target.value})}><MenuItem value="beginner">Beginner · forgiving</MenuItem><MenuItem value="standard">Standard · efficient</MenuItem><MenuItem value="expert">Expert · strongest lines</MenuItem></TextField></Grid>}
        <Grid size={{xs:12,sm:6}}><FormControlLabel control={<Switch checked={setup.play_first} onChange={e=>setSetup({...setup,play_first:e.target.checked})}/>} label="I play first"/></Grid>
      </Grid>{setup.opponent_type==='bot'&&setup.bot_deck_mode==='generated'&&<Alert severity="info" sx={{mt:2}}>The bot will build a different optimized deck from unassigned cards each game. It will not reserve those cards or save a deck to your library.</Alert>}<Button sx={{mt:2}} variant="contained" size="large" startIcon={busy?<CircularProgress size={18}/>:<PlayArrow/>} disabled={busy||!setup.player_deck_id||((setup.opponent_type==='human'||setup.bot_deck_mode==='existing')&&!setup.opponent_deck_id)} onClick={()=>void create()}>Start game</Button></CardContent></Card></Grid>
      <Grid size={{xs:12,md:5}}><Card variant="outlined"><CardContent><Stack direction="row" spacing={1} alignItems="center" mb={2}><History/><Typography variant="h5">Saved games</Typography></Stack>{!games.length?<Typography color="text.secondary">Your games will automatically save here.</Typography>:games.map(saved=><Stack key={saved.id} direction="row" alignItems="center" py={1} borderBottom="1px solid" borderColor="divider"><Box flex={1}><Typography fontWeight={900}>{saved.name}</Typography><Typography variant="caption" color="text.secondary">Turn {saved.state.turn} · {saved.status} · {saved.opponent_type==='bot'?`${saved.bot_difficulty} bot`:'private game'}</Typography></Box><Button onClick={()=>void resume(saved)}>Resume</Button><IconButton aria-label="Delete game" onClick={()=>void remove(saved.id)}><Delete/></IconButton></Stack>)}</CardContent></Card></Grid>
    </Grid>
  </Box>

  return <Box className="play-shell">
    <Stack direction="row" alignItems="center" gap={1} mb={1}><Button onClick={()=>{if(isGuest)location.href='?page=play';else{setGame(undefined);void load()}}}>← Games</Button><Typography variant="h5" flex={1}>{game.name} · {gameTitle}</Typography>{autoAdvancing&&<Chip color="info" label="Auto-passing…"/>}<Chip label={`Turn ${game.state.turn}`}/><Chip color={humanActive?'success':'secondary'} label={`${humanActive?'Your':game.opponent_type==='bot'?'Bot':bot?.name} turn · ${phase}`}/>{!isGuest&&<Tooltip title="Undo last action"><span><IconButton disabled={busy} onClick={()=>void undo()}><Replay/></IconButton></span></Tooltip>}<Tooltip title="Refresh saved state"><IconButton onClick={()=>request<Game>(gamePath,{headers:authHeaders}).then(setGame)}><Refresh/></IconButton></Tooltip></Stack>
    {inviteUrl&&<Alert severity="info" sx={{mb:1}} action={<Stack direction="row"><Button startIcon={<ContentCopy/>} onClick={()=>navigator.clipboard.writeText(inviteUrl)}>Copy invite</Button><Button onClick={()=>void rotateInvite()}>Replace link</Button></Stack>}>Private game ready. Send the expiring invite link to the other player; replacing it immediately revokes the old link.</Alert>}
    {error&&<Alert severity="error" sx={{mb:1}}>{error}</Alert>}
    <Paper className="play-table" elevation={8}>
      <Box className="player-hud opponent-hud"><Favorite color="error"/><Typography variant="h4">{bot?.life}</Typography>{!!bot?.poison&&<Chip size="small" color={bot.poison>=7?'error':'warning'} label={`☠ ${bot.poison}/10`}/>}<Box><Typography fontWeight={900}>{bot?.name}{game.opponent_type==='bot'?` · ${game.bot_difficulty}`:''}</Typography><Typography variant="caption">{bot?.library_count} library · {bot?.graveyard.length} graveyard{Object.values(bot?.commander_damage||{}).some(Boolean)?` · ${Math.max(...Object.values(bot?.commander_damage||{}))} commander`:''}</Typography></Box></Box>
      {!!bot?.command.length&&<Box className="command-zone opponent-command"><Typography variant="caption">COMMANDER</Typography>{bot.command.map(card=><ZoneCard key={card.instance_id} card={card}/>)}</Box>}
      <HiddenHand count={bot?.hand_count}/><Battlefield player={bot!} game={game} onCard={playCard}/>
      <Divider className="table-divider"><Chip icon={<Bolt/>} label={game.state.stack.length?`Stack · ${game.state.stack.at(-1)?.card.name}`:phase}/></Divider>
      <Battlefield player={player!} game={game} onCard={playCard} selectableIds={attackAction?attackerIds:blockAction?blockerIds:sacrificeAction?new Set(sacrificeAction.card_ids):legendaryAction?new Set(legendaryAction.card_ids):new Set()} selectedIds={attackAction?selectedIds:blockAction?new Set(Object.keys(blocks)):sacrificeAction?new Set(selectedSacrifices):new Set(selectedLegendary)} onSelect={card=>attackAction?toggleAttacker(card):blockAction?setChoosingBlocker(card.instance_id):sacrificeAction?setSelectedSacrifices(current=>current.includes(card.instance_id)?current.filter(id=>id!==card.instance_id):current.length<(sacrificeAction.amount||0)?[...current,card.instance_id]:current):setSelectedLegendary([card.instance_id])}/>
      <Stack direction="row" className="player-hand" justifyContent="center">{player?.hand.map(card=>{const choosing=!!handChoiceAction,selected=selectedDiscards.includes(card.instance_id);return <ZoneCard key={card.instance_id} card={card} selected={selected} legal={(choosing||!!game.legal_actions.find(item=>item.card_id===card.instance_id))&&!busy} onClick={()=>choosing?setSelectedDiscards(current=>selected?current.filter(id=>id!==card.instance_id):current.length<(handChoiceAction.amount||0)?[...current,card.instance_id]:current):playCard(card)}/>})}</Stack>
      {!!player?.command.length&&<Box className="command-zone"><Typography variant="caption">COMMANDER · tax {player.commander_casts*2}</Typography>{player.command.map(card=><ZoneCard key={card.instance_id} card={card} legal={!!game.legal_actions.find(item=>item.card_id===card.instance_id)&&!busy} onClick={()=>playCard(card)}/>)}</Box>}
      <Box className="player-hud"><Favorite color="error"/><Typography variant="h4">{player?.life}</Typography>{!!player?.poison&&<Chip size="small" color={player.poison>=7?'error':'warning'} label={`☠ ${player.poison}/10`}/>}<Box><Typography fontWeight={900}>You</Typography><Typography variant="caption">{player?.library_count} library · {player?.graveyard.length} graveyard{Object.values(player?.commander_damage||{}).some(Boolean)?` · ${Math.max(...Object.values(player?.commander_damage||{}))} commander`:''}</Typography></Box></Box>
      <Stack className="play-actions" direction="row" gap={1} flexWrap="wrap" useFlexGap>
        {legal('keep')&&<Button variant="contained" color="success" disabled={busy} onClick={()=>void act({type:'keep'})}>Keep hand</Button>}{legal('mulligan')&&<Button variant="outlined" disabled={busy} onClick={()=>void act({type:'mulligan'})}>Mulligan</Button>}
        {legal('resolve')&&<Button variant="contained" disabled={busy} onClick={()=>void act({type:'resolve'})}>Resolve {game.state.stack.at(-1)?.card.name}</Button>}
        {legal('pass_priority')&&<Button variant={game.state.stack.length?'contained':'outlined'} color="secondary" disabled={busy} onClick={()=>void act({type:'pass_priority'})}>{game.state.stack.length?'Pass priority':'Pass'}</Button>}
        {attackAction&&<><Chip color="warning" label={`${selectedAttackers.length} attacker${selectedAttackers.length===1?'':'s'} selected`}/><Button variant="contained" color="error" startIcon={<Bolt/>} disabled={busy} onClick={prepareAttack}>{selectedAttackers.length?'Choose defenders':'No attacks'}</Button><Button color="error" onClick={()=>setSelectedAttackers(attackAction.card_ids||[])}>Select all</Button></>}
        {blockAction&&<><Chip color={menaceInvalid?'error':'info'} label={`${Object.keys(blocks).length} blocker${Object.keys(blocks).length===1?'':'s'} assigned`}/><Button variant="contained" color="info" startIcon={<Shield/>} disabled={busy||menaceInvalid} onClick={()=>void act({type:'declare_blockers',blocks})}>{Object.keys(blocks).length?'Confirm blocks':'No blocks'}</Button><Button color="info" onClick={()=>setBlocks(automaticBlocks())}>Auto assign</Button></>}
        {discardAction&&<><Chip color="warning" label={`Discard ${selectedDiscards.length}/${discardAction.amount}`}/><Button variant="contained" color="warning" disabled={busy||selectedDiscards.length!==discardAction.amount} onClick={()=>void act({type:'discard_cards',card_ids:selectedDiscards})}>Confirm discard</Button></>}
        {mulliganBottomAction&&<><Chip color="warning" label={`Bottom ${selectedDiscards.length}/${mulliganBottomAction.amount}`}/><Button variant="contained" color="warning" disabled={busy||selectedDiscards.length!==mulliganBottomAction.amount} onClick={()=>void act({type:'bottom_mulligan_cards',card_ids:selectedDiscards})}>Keep this hand</Button></>}
        {sacrificeAction&&<><Chip color="error" label={`Sacrifice ${selectedSacrifices.length}/${sacrificeAction.amount}`}/><Button variant="contained" color="error" disabled={busy||selectedSacrifices.length!==sacrificeAction.amount} onClick={()=>void act({type:'sacrifice_permanents',card_ids:selectedSacrifices})}>Confirm sacrifice</Button></>}
        {legendaryAction&&<><Chip color="warning" label="Choose the legendary permanent to keep"/><Button variant="contained" color="warning" disabled={busy||selectedLegendary.length!==1} onClick={()=>void act({type:'choose_legendary',card_ids:selectedLegendary})}>Keep selected</Button></>}
        {legal('advance_phase')&&<Button variant="contained" disabled={busy} onClick={()=>void act({type:'advance_phase'})}>Next · {phases[(phases.findIndex(([key])=>key===game.state.phase)+1)%phases.length][1]}</Button>}
        {legal('resolve_combat_damage')&&<Button variant="contained" color="warning" disabled={busy} onClick={()=>void act({type:'resolve_combat_damage'})}>Deal combat damage</Button>}
        <Button size="small" onClick={()=>void act({type:'adjust_life',target_id:viewerId,amount:-1})}>−1 life</Button><Button size="small" onClick={()=>void act({type:'adjust_life',target_id:viewerId,amount:1})}>+1 life</Button><Button size="small" startIcon={<Build/>} onClick={()=>setToolsOpen(true)}>Table tools</Button>{legal('concede')&&<Button color="error" disabled={busy} onClick={()=>void act({type:'concede'})}>Concede</Button>}
      </Stack>
      <Paper className="game-log" variant="outlined"><Typography variant="overline">Game log</Typography>{game.state.log.slice(-8).reverse().map(entry=><Typography key={entry.id} variant="caption" display="block"><b>T{entry.turn}</b> · {entry.message}</Typography>)}</Paper>
    </Paper>
    <Dialog open={!!targetChoice} onClose={()=>setTargetChoice(undefined)}><DialogTitle>Choose a target</DialogTitle><DialogContent><Stack spacing={1} minWidth={320}>{targetChoice?.targets.map(target=><Button key={target.id} variant="outlined" onClick={()=>{void act({type:targetChoice.action.type,card_id:targetChoice.action.card_id,ability_index:targetChoice.action.ability_index,target_id:target.id,cost_card_ids:targetChoice.action.cost_card_ids||[],chosen_modes:targetChoice.action.chosen_modes||[],source:targetChoice.action.source});setTargetChoice(undefined)}}>{target.name} · {target.controller_id===viewerId?'yours':'opponent'}</Button>)}</Stack></DialogContent><DialogActions><Button onClick={()=>setTargetChoice(undefined)}>Cancel</Button></DialogActions></Dialog>
    <Dialog open={!!abilityChoices.length} onClose={()=>setAbilityChoices([])} fullWidth maxWidth="sm"><DialogTitle>Choose an ability</DialogTitle><DialogContent><Stack spacing={1}>{abilityChoices.map(action=><Button key={`${action.type}-${action.ability_index}`} variant="outlined" sx={{justifyContent:'flex-start',textAlign:'left'}} onClick={()=>{setAbilityChoices([]);executeCardAction(action)}}>{action.label||`${action.type==='activate_loyalty'?'Loyalty ability':'Activate'} ${action.ability_index!==undefined?Number(action.ability_index)+1:''}`}</Button>)}</Stack></DialogContent><DialogActions><Button onClick={()=>setAbilityChoices([])}>Cancel</Button></DialogActions></Dialog>
    <Dialog open={!!modeChoice} onClose={()=>{setModeChoice(undefined);setSelectedModes([])}} fullWidth maxWidth="sm"><DialogTitle>Choose {modeChoice?.mode_min===modeChoice?.mode_max?modeChoice?.mode_min:`${modeChoice?.mode_min}–${modeChoice?.mode_max}`} mode{modeChoice?.mode_max===1?'':'s'}</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>Select how {player?.hand.find(card=>card.instance_id===modeChoice?.card_id)?.name||'this spell'} should resolve.{modeChoice?.mode_repeatable?' A mode may be chosen more than once.':''}</Typography><Stack spacing={1.5}>{modeChoice?.modes?.map((mode:GameMode)=>{const count=selectedModes.filter(index=>index===mode.index).length,selected=count>0;return <Button key={mode.index} variant={selected?'contained':'outlined'} sx={{justifyContent:'flex-start',textAlign:'left',py:1.5}} onClick={()=>setSelectedModes(current=>{if(modeChoice.mode_repeatable){if(current.length<(modeChoice.mode_max||1))return[...current,mode.index];const last=current.lastIndexOf(mode.index);return last<0?current:current.filter((_,index)=>index!==last)}return selected?current.filter(index=>index!==mode.index):current.length<(modeChoice.mode_max||1)?[...current,mode.index]:current})}>{count>1?`${count}× `:''}{mode.label}</Button>})}</Stack></DialogContent><DialogActions><Button onClick={()=>{setModeChoice(undefined);setSelectedModes([])}}>Cancel</Button><Button variant="contained" disabled={selectedModes.length<(modeChoice?.mode_min||1)||selectedModes.length>(modeChoice?.mode_max||1)} onClick={confirmModes}>Choose modes</Button></DialogActions></Dialog>
    <Dialog open={!!modalTargetChoice} onClose={()=>setModalTargetChoice(undefined)} fullWidth maxWidth="sm"><DialogTitle>Choose target · mode {modalTargetChoice?modalTargetChoice.position+1:1}</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>{modalTargetChoice?.modes[modalTargetChoice.position]?.label}</Typography><Stack spacing={1}>{modalTargetChoice?.modes[modalTargetChoice.position]?.targets?.filter(target=>!modalTargetChoice.action.mode_distinct_targets||!modalTargetChoice.targets.includes(target.id)).map(target=><Button key={target.id} variant="outlined" onClick={()=>chooseModalTarget(target.id)}>{target.name} · {target.controller_id===viewerId?'yours':'opponent'}</Button>)}</Stack></DialogContent><DialogActions><Button onClick={()=>setModalTargetChoice(undefined)}>Cancel</Button></DialogActions></Dialog>
    <Dialog open={!!costChoice} onClose={()=>{setCostChoice(undefined);setSelectedCosts([])}} fullWidth maxWidth="md"><DialogTitle>{costChoice?.cost_kind==='discard'?'Choose cards to discard':'Choose permanents to sacrifice'}</DialogTitle><DialogContent><Alert severity="warning" sx={{mb:2}}>{costChoice?.label}</Alert><Stack direction="row" gap={1.5} flexWrap="wrap" justifyContent="center">{(costChoice?.cost_options||[]).map(id=>{const card=[...(player?.hand||[]),...(player?.battlefield||[])].find(item=>item.instance_id===id);if(!card)return null;const selected=selectedCosts.includes(id);return <Paper component="button" type="button" key={id} variant="outlined" onClick={()=>setSelectedCosts(current=>selected?current.filter(cardId=>cardId!==id):current.length<(costChoice?.cost_amount||1)?[...current,id]:current)} sx={{width:145,p:1,cursor:'pointer',color:'text.primary',bgcolor:'background.paper',borderColor:selected?'error.main':'divider',boxShadow:selected?'0 0 0 2px rgba(255,91,106,.4)':'none'}}>{card.image_url&&<Box component="img" src={card.image_url} alt={card.name} sx={{width:'100%',aspectRatio:'488 / 680',objectFit:'cover',display:'block'}}/>}<Typography fontWeight={900} mt={1} noWrap>{card.name}</Typography><Typography variant="caption" color="text.secondary">{card.type_line}</Typography></Paper>})}</Stack></DialogContent><DialogActions><Button onClick={()=>{setCostChoice(undefined);setSelectedCosts([])}}>Cancel</Button><Button variant="contained" color="error" disabled={busy||selectedCosts.length!==(costChoice?.cost_amount||0)} onClick={()=>{if(!costChoice)return;const action={...costChoice,cost_card_ids:selectedCosts};setCostChoice(undefined);setSelectedCosts([]);submitCardAction(action)}}>Pay cost ({selectedCosts.length}/{costChoice?.cost_amount||0})</Button></DialogActions></Dialog>
    <Dialog open={!!blockOrderAction} fullWidth maxWidth="md" disableEscapeKeyDown><DialogTitle>Order combat damage</DialogTitle><DialogContent><Alert severity="info" sx={{mb:2}}>Your attacker deals lethal damage to each blocker in this order before assigning damage to the next.</Alert><Stack spacing={3}>{blockOrderAction?.groups?.map(group=>{const defaults=group.blockers.map(card=>card.instance_id),order=blockOrders[group.attacker.instance_id]||defaults;return <Box key={group.attacker.instance_id}><Typography fontWeight={900} mb={1}>{group.attacker.name} ({group.attacker.power}/{group.attacker.toughness})</Typography><Stack direction="row" gap={1.5} flexWrap="wrap">{order.map((id,index)=>{const blocker=group.blockers.find(card=>card.instance_id===id)!;return <Paper key={id} variant="outlined" sx={{width:140,p:1}}><Box component="img" src={blocker.image_url||''} alt={blocker.name} sx={{width:'100%',aspectRatio:'488 / 680',objectFit:'cover',display:'block'}}/><Typography fontWeight={800} noWrap mt={.75}>{index+1}. {blocker.name}</Typography><Typography variant="caption">{blocker.power}/{blocker.toughness}</Typography><Stack direction="row" justifyContent="space-between"><IconButton size="small" disabled={index===0} onClick={()=>moveBlocker(group.attacker.instance_id,defaults,index,-1)}><ArrowUpward/></IconButton><IconButton size="small" disabled={index===order.length-1} onClick={()=>moveBlocker(group.attacker.instance_id,defaults,index,1)}><ArrowDownward/></IconButton></Stack></Paper>})}</Stack></Box>})}</Stack></DialogContent><DialogActions><Button variant="contained" disabled={busy} onClick={()=>void act({type:'order_blockers',block_orders:Object.fromEntries((blockOrderAction?.groups||[]).map(group=>[group.attacker.instance_id,blockOrders[group.attacker.instance_id]||group.blockers.map(card=>card.instance_id)]))})}>Assign damage</Button></DialogActions></Dialog>
    <Dialog open={!!wardAction} fullWidth maxWidth={wardAction?.cost_type==='discard'?'md':'xs'} disableEscapeKeyDown><DialogTitle>Ward — {wardAction?.source_name}</DialogTitle><DialogContent><Alert severity="warning" sx={{mb:wardAction?.cost_type==='discard'?2:0}}>Pay {wardAction?.label||wardAction?.mana_cost} or your spell or ability will be countered.</Alert>{wardAction?.cost_type==='discard'&&<Stack direction="row" gap={1.5} flexWrap="wrap" justifyContent="center">{player?.hand.map(card=>{const selected=selectedDiscards.includes(card.instance_id);return <Paper component="button" type="button" key={card.instance_id} variant="outlined" onClick={()=>setSelectedDiscards(current=>selected?current.filter(id=>id!==card.instance_id):current.length<(wardAction.amount||1)?[...current,card.instance_id]:current)} sx={{width:130,p:1,cursor:'pointer',color:'text.primary',bgcolor:'background.paper',borderColor:selected?'warning.main':'divider',boxShadow:selected?'0 0 0 2px rgba(255,190,70,.45)':'none'}}><Box component="img" src={card.image_url||''} alt={card.name} sx={{width:'100%',aspectRatio:'488 / 680',objectFit:'cover',display:'block'}}/><Typography fontWeight={800} noWrap mt={.75}>{card.name}</Typography></Paper>})}</Stack>}</DialogContent><DialogActions><Button color="error" disabled={busy} onClick={()=>void act({type:'decline_ward'})}>Don’t pay</Button><Button variant="contained" disabled={busy||!payWardAction||(wardAction?.cost_type==='discard'&&selectedDiscards.length!==(wardAction.amount||1))} onClick={()=>void act({type:'pay_ward',card_ids:selectedDiscards})}>Pay {wardAction?.label||wardAction?.mana_cost}</Button></DialogActions></Dialog>
    <Dialog open={!!triggerTargetAction||!!skipTriggerAction} fullWidth maxWidth="md" disableEscapeKeyDown><DialogTitle>{triggerTargetAction?.source_name||skipTriggerAction?.source_name} triggered</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>{triggerTargetAction?.label||'This trigger has no legal target.'}</Typography><Stack direction="row" gap={1.5} flexWrap="wrap" justifyContent="center">{triggerTargetAction?.targets?.map(target=>{const card=game.state.players.flatMap(owner=>owner.battlefield).find(item=>item.instance_id===target.id);return <Paper component="button" type="button" key={target.id} variant="outlined" onClick={()=>void act({type:'choose_trigger_target',target_id:target.id})} sx={{width:150,p:1,cursor:'pointer',color:'text.primary',bgcolor:'background.paper','&:hover':{borderColor:'primary.main'}}}>{card?.image_url&&<Box component="img" src={card.image_url} alt={target.name} sx={{width:'100%',aspectRatio:'488 / 680',objectFit:'cover',display:'block'}}/>}<Typography fontWeight={900} mt={card?.image_url?.length?1:0}>{target.name}</Typography><Typography variant="caption" color="text.secondary">{target.controller_id===viewerId?'Yours':'Opponent'}</Typography></Paper>})}</Stack></DialogContent>{skipTriggerAction&&<DialogActions><Button variant="contained" onClick={()=>void act({type:'skip_trigger'})}>Continue</Button></DialogActions>}</Dialog>
    <Dialog open={!!scryAction} fullWidth maxWidth="md" disableEscapeKeyDown><DialogTitle>{scryAction?.type==='surveil'?'Surveil':'Scry'} {scryAction?.amount}</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>Arrange the cards from top to bottom, then choose which ones go {scryAction?.type==='surveil'?'to your graveyard':'beneath your library'}.</Typography><Stack direction="row" gap={2} flexWrap="wrap" justifyContent="center">{orderedScryCards.map((card,index)=><Paper key={card.instance_id} variant="outlined" sx={{width:170,p:1.25,borderColor:scryBottom.includes(card.instance_id)?'warning.main':'success.main'}}><Box component="img" src={card.image_url||''} alt={card.name} sx={{width:'100%',aspectRatio:'488 / 680',objectFit:'cover',display:'block'}}/><Typography fontWeight={900} mt={1} noWrap>{card.name}</Typography><Chip size="small" color={scryBottom.includes(card.instance_id)?'warning':'success'} label={scryBottom.includes(card.instance_id)?scryAction?.type==='surveil'?'Graveyard':'Bottom':'Top'} sx={{my:1}}/><Stack direction="row" justifyContent="space-between"><IconButton size="small" disabled={index===0} onClick={()=>moveScry(index,-1)}><ArrowUpward/></IconButton><Button size="small" onClick={()=>setScryBottom(current=>current.includes(card.instance_id)?current.filter(id=>id!==card.instance_id):[...current,card.instance_id])}>{scryBottom.includes(card.instance_id)?'Keep top':scryAction?.type==='surveil'?'Put in graveyard':'Put bottom'}</Button><IconButton size="small" disabled={index===orderedScryCards.length-1} onClick={()=>moveScry(index,1)}><ArrowDownward/></IconButton></Stack></Paper>)}</Stack></DialogContent><DialogActions><Button variant="contained" disabled={busy} onClick={()=>{const order=scryOrder.length?scryOrder:scryAction?.card_ids||[],away=order.filter(id=>scryBottom.includes(id));void act({type:scryAction?.type,top_ids:order.filter(id=>!scryBottom.includes(id)),...(scryAction?.type==='surveil'?{graveyard_ids:away}:{bottom_ids:away})})}}>Confirm {scryAction?.type}</Button></DialogActions></Dialog>
    <Dialog open={!!choosingBlocker} onClose={()=>setChoosingBlocker(undefined)}><DialogTitle>Choose what to block</DialogTitle><DialogContent><Stack spacing={1} minWidth={320}>{(blockAction?.legal_blocks?.[choosingBlocker||'']||[]).map(attackerId=>{const attacker=bot?.battlefield.find(card=>card.instance_id===attackerId);return <Button key={attackerId} variant={blocks[choosingBlocker||'']===attackerId?'contained':'outlined'} onClick={()=>assignBlock(attackerId)}>{attacker?.name||'Attacking creature'}{attacker?.power&&attacker?.toughness?` · ${attacker.power}/${attacker.toughness}`:''}</Button>})}</Stack></DialogContent><DialogActions><Button onClick={()=>assignBlock()}>Don’t block</Button><Button onClick={()=>setChoosingBlocker(undefined)}>Cancel</Button></DialogActions></Dialog>
    <Dialog open={attackDialog} onClose={()=>setAttackDialog(false)} fullWidth maxWidth="sm"><DialogTitle>Choose each attacker’s defender</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{selectedAttackers.map(attackerId=>{const attacker=player?.battlefield.find(card=>card.instance_id===attackerId);return <TextField key={attackerId} select fullWidth label={attacker?.name||'Attacker'} value={attackTargets[attackerId]||''} onChange={event=>setAttackTargets(current=>({...current,[attackerId]:event.target.value}))}>{attackAction?.defenders?.map(defender=><MenuItem key={defender.id} value={defender.id}>{defender.kind==='player'?'Player':`Planeswalker · ${defender.name}`}</MenuItem>)}</TextField>})}</Stack></DialogContent><DialogActions><Button onClick={()=>setAttackDialog(false)}>Cancel</Button><Button variant="contained" color="error" disabled={selectedAttackers.some(id=>!attackTargets[id])} onClick={()=>{setAttackDialog(false);void act({type:'declare_attackers',attacker_ids:selectedAttackers,attack_targets:attackTargets})}}>Attack</Button></DialogActions></Dialog>
    <Dialog open={toolsOpen} onClose={()=>setToolsOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Manual table tools</DialogTitle><DialogContent><Alert severity="info" sx={{mb:2}}>Use these controls when a card interaction is not automated yet. Every correction is recorded in the game log and can be undone.</Alert><Typography variant="overline">Create token</Typography><Stack direction={{xs:'column',sm:'row'}} gap={1} mb={2}><TextField label="Token name" value={toolForm.token_name} onChange={e=>setToolForm({...toolForm,token_name:e.target.value})}/><TextField label="Power" type="number" value={toolForm.power} onChange={e=>setToolForm({...toolForm,power:Number(e.target.value)})}/><TextField label="Toughness" type="number" value={toolForm.toughness} onChange={e=>setToolForm({...toolForm,toughness:Number(e.target.value)})}/><Button variant="contained" onClick={()=>void act({type:'create_token',token_name:toolForm.token_name,power:toolForm.power,toughness:toolForm.toughness})}>Create</Button></Stack><Divider sx={{my:2}}/><Typography variant="overline">Counter or move a visible card</Typography><TextField select fullWidth label="Card" value={toolForm.target_id} onChange={e=>setToolForm({...toolForm,target_id:e.target.value})} sx={{mb:1}}>{visibleCards.map(({card,owner,zone})=><MenuItem key={`${zone}-${card.instance_id}`} value={card.instance_id}>{card.name} · {owner} · {zone}</MenuItem>)}</TextField><Stack direction={{xs:'column',sm:'row'}} gap={1}><TextField label="Counter" value={toolForm.counter_name} onChange={e=>setToolForm({...toolForm,counter_name:e.target.value})}/><TextField label="Amount" type="number" value={toolForm.amount} onChange={e=>setToolForm({...toolForm,amount:Number(e.target.value)})}/><Button disabled={!toolForm.target_id} onClick={()=>void act({type:'add_counter',target_id:toolForm.target_id,counter_name:toolForm.counter_name,amount:toolForm.amount})}>Apply counter</Button></Stack><Stack direction={{xs:'column',sm:'row'}} gap={1} mt={1}><TextField select label="Destination" value={toolForm.destination} onChange={e=>setToolForm({...toolForm,destination:e.target.value})}><MenuItem value="hand">Hand</MenuItem><MenuItem value="battlefield">Battlefield</MenuItem><MenuItem value="graveyard">Graveyard</MenuItem><MenuItem value="exile">Exile</MenuItem></TextField><Button disabled={!toolForm.target_id} onClick={()=>void act({type:'move_zone',target_id:toolForm.target_id,destination:toolForm.destination})}>Move card</Button></Stack></DialogContent><DialogActions><Button onClick={()=>setToolsOpen(false)}>Done</Button></DialogActions></Dialog>
    <Dialog open={game.state.status==='complete'}><DialogTitle>{winner?.id===viewerId?'Victory!':'Game over'}</DialogTitle><DialogContent><Typography>{winner?.name} won on turn {game.state.turn}.</Typography></DialogContent><DialogActions><Button onClick={()=>{location.href='?page=play'}}>Return to games</Button></DialogActions></Dialog>
  </Box>
}
