import { useEffect, useState } from 'react'
import { DeleteOutline, Search, VisibilityOff } from '@mui/icons-material'
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogContent, DialogTitle, Grid, InputAdornment, Stack, TextField, Typography } from '@mui/material'
import { API, request } from '../api'
import type { Candidate, Deck, Defaults } from '../types'

type Review={id:string;confidence:number;ocr_text:string|null;created_at:string;candidates:Candidate[];defaults:Defaults}
const foilOnly=(candidate:Candidate)=>!candidate.finishes.includes('nonfoil')&&candidate.finishes.some(finish=>finish==='foil'||finish==='etched')
const displayPrice=(candidate:Candidate,foil:boolean)=>Number(((foil||foilOnly(candidate))?(candidate.foil_market_price||candidate.market_price):candidate.market_price)||0).toFixed(2)

export default function ReviewQueue(){
  const [items,setItems]=useState<Review[]>([]),[decks,setDecks]=useState<Deck[]>([]),[manual,setManual]=useState<Review|null>(null),[query,setQuery]=useState(''),[matches,setMatches]=useState<Candidate[]>([]),[error,setError]=useState<string>()
  const [preview,setPreview]=useState<Review|null>(null)
  const load=()=>request<Review[]>('/reviews').then(setItems)
  useEffect(()=>{void load();void request<Deck[]>('/decks').then(setDecks)},[])
  const ignore=async(id:string)=>{await request(`/reviews/${id}/ignore`,{method:'POST'});load()}
  const remove=async(id:string)=>{await request(`/reviews/${id}`,{method:'DELETE'});load()}
  const resolve=async(item:Review,candidate:Candidate)=>{await request(`/reviews/${item.id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate})});setManual(null);setMatches([]);load()}
  const search=async()=>{setError(undefined);try{setMatches(await request<Candidate[]>(`/reviews/search?q=${encodeURIComponent(query)}&lang=${manual?.defaults.language||'en'}`))}catch(e){setError(e instanceof Error?e.message:'Search failed')}}
  return <>
    <Typography variant="h4">Review queue</Typography><Typography color="text.secondary" mb={3}>Hard scans wait here without interrupting a batch.</Typography>
    <Grid container spacing={2}>{items.map(item=><Grid size={{xs:12,lg:6}} key={item.id}><Card><CardContent>
      <Stack direction="row" justifyContent="space-between"><Chip color={item.confidence>=70?'warning':'error'} label={`${item.confidence.toFixed(1)}% confidence`}/><Stack direction="row"><Button size="small" startIcon={<VisibilityOff/>} onClick={()=>ignore(item.id)}>Ignore</Button><Button size="small" color="error" startIcon={<DeleteOutline/>} onClick={()=>remove(item.id)}>Delete</Button></Stack></Stack>
      <Stack direction={{xs:'column',sm:'row'}} spacing={1.5} mt={2}><Box onClick={()=>setPreview(item)} sx={{width:{xs:'100%',sm:180},height:252,flexShrink:0,display:'grid',placeItems:'center',overflow:'hidden',bgcolor:'#050807',border:'1px solid',borderColor:'divider',borderRadius:1.5,cursor:'zoom-in'}}><Box component="img" src={`${API}/api/reviews/${item.id}/image`} sx={{display:'block',width:'100%',height:'100%',objectFit:'contain'}}/></Box><Box flex={1} minWidth={0}><Stack direction="row" spacing={.75} flexWrap="wrap" mb={1}><Chip size="small" label={item.defaults.condition.replaceAll('_',' ')}/><Chip size="small" label={item.defaults.language.toUpperCase()}/>{item.defaults.foil&&<Chip size="small" color="warning" label="Foil"/>}<Chip size="small" label={`Deck · ${decks.find(deck=>deck.id===item.defaults.deck_id)?.name||'None'}`}/><Chip size="small" label={`Storage · ${item.defaults.storage_location}`}/></Stack><Box sx={{maxHeight:112,overflow:'auto',p:1,bgcolor:'action.hover',borderRadius:1}}><Typography display="block" variant="caption" color="text.secondary" sx={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>OCR: {item.ocr_text||'No readable text'}</Typography></Box>{item.candidates.map(c=><Stack key={c.scryfall_id} direction="row" spacing={1} alignItems="center" mt={1}><Box component="img" src={c.image_url||''} sx={{width:42,flexShrink:0}}/><Box flex={1} minWidth={0}><Typography fontWeight={700}>{c.name}</Typography><Typography variant="body2">{c.set_name} #{c.collector_number} · {c.language.toUpperCase()}</Typography></Box><Button variant="contained" size="small" onClick={()=>resolve(item,c)}>Choose</Button></Stack>)}<Button startIcon={<Search/>} sx={{mt:2}} onClick={()=>{setManual(item);setQuery('');setMatches([])}}>Search manually</Button></Box></Stack>
    </CardContent></Card></Grid>)}</Grid>
    {!items.length&&<Typography color="text.secondary" textAlign="center" mt={8}>Nothing needs review.</Typography>}
    <Dialog open={!!manual} onClose={()=>setManual(null)} fullWidth maxWidth="md"><DialogTitle>Find the exact printing</DialogTitle><DialogContent><Stack direction="row" spacing={1} mt={1}><TextField autoFocus fullWidth placeholder="Card name" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&query.length>=2)void search()}} slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/><Button variant="contained" disabled={query.length<2} onClick={search}>Search</Button></Stack>{error&&<Alert severity="error" sx={{mt:2}}>{error}</Alert>}<Grid container spacing={2} mt={1}>{matches.map(c=><Grid size={{xs:12,sm:6}} key={c.scryfall_id}><Card variant="outlined"><CardContent><Stack direction="row" spacing={2}><Box component="img" src={c.image_url||''} sx={{width:75}}/><Box flex={1}><Typography fontWeight={800}>{c.name}</Typography><Typography variant="body2">{c.set_name} #{c.collector_number} · {c.language.toUpperCase()}</Typography><Typography color="primary.main">${displayPrice(c,manual?.defaults.foil||false)}{(manual?.defaults.foil||foilOnly(c))?' · foil':''}{foilOnly(c)?' only':''}</Typography><Button size="small" variant="contained" sx={{mt:1}} onClick={()=>manual&&resolve(manual,c)}>Choose printing</Button></Box></Stack></CardContent></Card></Grid>)}</Grid></DialogContent></Dialog>
    <Dialog open={!!preview} onClose={()=>setPreview(null)} fullWidth maxWidth="md"><DialogTitle>Captured scan</DialogTitle><DialogContent sx={{display:'grid',placeItems:'center',bgcolor:'#050807',p:2}}>{preview&&<Box component="img" src={`${API}/api/reviews/${preview.id}/image`} sx={{display:'block',maxWidth:'100%',maxHeight:'75vh',objectFit:'contain'}}/>}</DialogContent></Dialog>
  </>
}
